info:
  name: GetTaskById
  type: http
  seq: 2

http:
  method: GET
  url: http://localhost:3000/tasks/70a0dbfd-e429-45a2-93c9-7438442e6482
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
