info:
  name: postTaskDone
  type: http
  seq: 4

http:
  method: POST
  url: http://localhost:3000/tasks/dc6f9a97-9135-451a-a41e-37123b2e429c/done
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
