info:
  name: putTaskById
  type: http
  seq: 5

http:
  method: PUT
  url: http://localhost:3000/tasks/c529610c-ab1d-4c68-8dc4-f6309b64fa32
  body:
    type: json
    data: |2-
      
        {
          "title": "Test Task",
          "description": "ljk"
        }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
