info:
  name: putTaskById
  type: http
  seq: 5

http:
  method: PUT
  url: http://localhost:3000/tasks/74b096db-d87e-4955-9fe8-af8ae2b1014d
  body:
    type: json
    data: |2-
      
        {
          "title": "Test Task",
          "description": "ljk",
          "dueDate":"2026-04-01T12:00:00.000Z"
        }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
